---
- name: create AWS EC2 instance for deployment        
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:

    - name: create EC2 instance
      ec2:
         key_name: website_access
         group: webserver_access_group
         instance_type: t2.micro
         image: ami-10547475
         wait: true
         count: 1
         region: us-east-2b
         #vpc_subnet_id: subnet-29e63245
         #assign_public_ip: yes 
      register: ec2
      
    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ ec2.instances }}"
      
#    - name: configuration play
#      hosts: ec2hosts
#      user: ubuntu
#      
#      tasks:        
