---
- name: setup django+gunicorn+nginx+postgres+git development environment
  hosts: ansible_host
  user: ubuntu
  
  tasks:
    - name: apt-get install packages
      apt: name={{item}} state=installed
      become: yes
      become_user: root
      become_method: sudo
      with_items: 
        - python
        - virtualenv
        - git
        - nginx
        - postgresql
        - python-pip
        
    - name: kill any gunicorn processes
      shell: pkill gunicorn
      ignore_errors: true
    
    - name: remove existing backup
      command: rm -rf ~/website.bak
      
    - name: back-up and remove existing directory
      command: mv ~/website ~/website.bak
      ignore_errors: true

    - name: clone git repo
      git: 
        repo: git@github.com:nam20485/website.git
        dest: ~/website
        #force: yes
        
    #- name: upgrade pip
    #  command: pip install --upgrade pip
        
    - name: pip install python packages
      pip: 
        requirements: ~/website/requirements.txt
           
    - name: run gunicorn from config file
      gunicorn:
        app: 'website.wsgi'
        chdir: '~/website'
        conf: '~/website/gunicorn.conf'
